MVCProje/MVCProje/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeDB;
using MVCProje.Models;

namespace MVCProje.Controllers
{
    public class ClaimController : Controller
    {
        // GET: Claim
        public ActionResult Index()
        {

            try
            {
                using (var db =new ProjeEntities())
                {
                    var emp = Session["emp"] as Employee;
                    var ct = db.ClaimTypes.ToList();
                    List<MVCProje.Models.ClaimType> ctt =new List<MVCProje.Models.ClaimType>();
                    foreach (ProjeDB.ClaimType item in ct)
                    {
                       ctt.Add(new Models.ClaimType
                       {
                        Id=item.Id,
                        Name=item.Name
                       });
                    }
                  
                  
                    List<Models.ClaimOther> co =new List<Models.ClaimOther>();
                    List<Models.ClaimHoliday> ch = new List<Models.ClaimHoliday>();
                    var clistother = db.EmployeeClaims.Where(x => x.EmployeeId == emp.Id).Where(z=>z.ClaimTypeId==1).ToList();
                    var clistholiday = db.EmployeeClaims.Where(x => x.EmployeeId == emp.Id).Where(z => z.ClaimTypeId == 2).ToList();

                    var dbo = DBO.GetInstance();


                    foreach (var item in clistholiday)
                    {
                        var returnch = dbo.getCholidaybyId(item.Id);
                        Models.ClaimHoliday mch = new Models.ClaimHoliday();
                        mch.Id = returnch.Id;
                        mch.Start = Convert.ToDateTime(returnch.StartDate);
                        mch.Finish = Convert.ToDateTime(returnch.FinishDate);
                        mch.Accept = (Boolean)returnch.Accept;
                        ch.Add(mch);

                    }

                    foreach (var item in clistother)
                    {
                        var returnch = dbo.getCOtherbyId(item.Id);
                        Models.ClaimOther mco = new Models.ClaimOther();
                        mco.Id = returnch.Id;
                        mco.Details = returnch.Details;
                        co.Add(mco);

                    }

                    MVCProje.Models.ClaimModel Cmodel = new ClaimModel();
                    Cmodel.ClaimTypeModel = ctt;
                    Cmodel.ClaimHolidayModel = ch;
                    Cmodel.ClaimOtherModel = co;

                    return View(Cmodel);
                   
                }
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        public JsonResult addClaim(string _details, string _typename)
        {
            try
            {
                using (var db = new ProjeEntities())
                {

                    int _typeid = db.ClaimTypes.Where(z => z.Name == _typename).Select(x => x.Id).FirstOrDefault();
                    var emp = Session["emp"] as Employee;
                    var dba = DBO.GetInstance();
                    var st = dba.addEmpClaim(_typeid,emp.Id);
                    dba.addClaimOther(_details, st.Id);
                    return Json("");
                }
            }
            catch (Exception)
            {

                throw;
            }
            
        }
       

         public JsonResult addHoliday(string _typename,string _start, string _finish)
        {
            try
            {
                using (var db = new ProjeEntities())
                {
                    int _typeid = db.ClaimTypes.Where(z => z.Name == _typename).Select(x => x.Id).FirstOrDefault();
                    var emp = Session["emp"] as Employee;
                    var dba = DBO.GetInstance();
                    var st = dba.addEmpClaim(_typeid, emp.Id);
                    dba.addHoliday(st.Id, _start, _finish);
                    return Json("");
                }
            }
            catch (Exception)
            {

                throw;
            }
        }

            public ActionResult returnOther()
        {
            try
            {
                using (var db = new ProjeEntities())
                {
                   
                    return PartialView("_OtherClaim");
                }
            }
            catch (Exception)
            {

                throw;
            }



        }


        public ActionResult returnHoliday()
        {
            try
            {
                using (var db = new ProjeEntities())
                {

                    return PartialView("_HolidayClaim");
                }
            }
            catch (Exception)
            {

                throw;
            }
        }
        
    }
}

MVCProje/MVCProje/Views/Claim/Index.cshtml
@{
    ViewBag.Title = "Index";
    if (Session["Check"].ToString() != "Emp")
    {
        Response.Redirect("~/Login/Index");
    }
}
@model MVCProje.Models.ClaimModel
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                Claim
            </header>
            <div class="panel-body">
                <form class="form-horizontal" id="default">
                    <fieldset title="Step 2" class="step" id="default-step-1" style="display: block;">
                        <legend> </legend>
                        <div class="form-group">

                            <label class="col-sm-2 control-label col-lg-2" for="inputSuccess">Type</label>
                            <div class="col-lg-10">
                                <select class="form-control m-bot15" id="_type" onchange="getOther(this.value)">


                                    @foreach (var item in Model.ClaimTypeModel)
                                    {

                                        <option  id="@item.Id">@item.Name</option>
                                    }

                                </select>
                            </div>


                            <div id="content">
                                

                            </div>
                           
                           
                        </div>
                      
                    </fieldset>
                </form>
            </div>
        </section>
    </div>
</div>
<div class="row">

    <section class="panel">
        <header class="panel-heading">
            <h1>Claim</h1>
        </header>
        <div class="panel-body">
            <div class="adv-table">
                <form action="User/AddEmployee" method="post">
                    <table border="0" class="display table table-bordered" id="hidden-table-info1">
                        <thead>
                            <tr>
                                <th>Start</th>
                                <th>Finish</th>
                                <th>Accetp</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ClaimHolidayModel)
                            {
                                <tr>
                                    <td>@item.Start</td>
                                    <td>@item.Finish</td>
                                    <td>@item.Accept</td>
                                </tr>
                            }
                                

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </section>
</div>

<div class="row">

    <section class="panel">
        <header class="panel-heading">
            <h1>Claim</h1>
        </header>
        <div class="panel-body">
            <div class="adv-table">
                <form action="User/AddEmployee" method="post">
                    <table border="0" class="display table table-bordered" id="hidden-table-info2">
                        <thead>
                            <tr>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ClaimOtherModel)
                            {
                                <tr>
                                    <td>@item.Details</td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </section>
</div>





@section script{
    <script>
        function addOther() {

            var data = {

                _typename: $('#_type').val(),
                _details: $('#_textArea').val()
            };
            $.ajax
                ({
                    url: '@Url.Action("addClaim", "Claim")',
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    processData: false,
                    success: window.location.assign("/Claim/Index")
                }
                );

        }
        function addHoliday() {

            var data = {
                _typename: $('#_type').val(),
                _finish: $('#_finish').val(),
                _start: $('#_start').val()
            };
            $.ajax
                ({
                    url: '@Url.Action("addHoliday", "Claim")',
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    processData: false,
                    success: window.location.assign("/Claim/Index") /*$("#_textArea").val(null)*/
                }
                );

        }
        function getOther(selectedtype) {
            if (selectedtype == "Other") {
                $.ajax({
                    url: '@Url.Action("returnOther", "Claim")',
             type: 'POST',
             dataType: 'html',
             data: {},
             success: function (data) {
                  $("#content").html(null);
                 $("#content").html(data);

             },
             error: function (hata, ajaxOptions, thrownError) {
                 alert(hata.status);
                 alert(thrownError);
                 alert(hata.responseText);
             }
            });
            }
            if (selectedtype == "İzinİstek")
                {
            $.ajax({
                url: '@Url.Action("returnHoliday", "Claim")',
             type: 'POST',
             dataType: 'html',
             data: {},
             success: function (data) {
                 $("#content").html(null);
                 $("#content").html(data);

             },
             error: function (hata, ajaxOptions, thrownError) {
                 alert(hata.status);
                 alert(thrownError);
                 alert(hata.responseText);
             }
            });
            }
        }
        getOther("Other");

    </script>
    
<script type="text/javascript">
         /* Formating function for row details */


         $(document).ready(function () {

             var oTable = $('#hidden-table-info1').dataTable({
                 "aoColumnDefs": [
                     { "bSortable": false, "aTargets": [0] }
                 ],
                 "aaSorting": [[1, 'asc']]
             });


        });
         $(document).ready(function () {

             var oTable = $('#hidden-table-info2').dataTable({
                 "aoColumnDefs": [
                     { "bSortable": false, "aTargets": [0] }
                 ],
                 "aaSorting": [[1, 'asc']]
             });


         });
</script>

<script src="../../content/js/jquery.scrollto.min.js"></script>
<script src="../../content/js/jquery.nicescroll.js" type="text/javascript"></script>
<script src="../../Content/js/respond.min.js"></script>
<script type="text/javascript" language="javascript" src="../../Content/assets/advanced-datatable/media/js/jquery.dataTables.js"></script>
<script src="../../Content/js/common-scripts.js"></script>
<script class="include" type="text/javascript" src="../../Content/js/jquery.dcjqaccordion.2.7.js"></script>
    <!--this page plugins-->
<script type="text/javascript" src="../../Content/assets/fuelux/js/spinner.min.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-daterangepicker/moment.min.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/jquery-multi-select/js/jquery.multi-select.js"></script>
<script type="text/javascript" src="../../Content/assets/jquery-multi-select/js/jquery.quicksearch.js"></script>
<!--common script for all pages-->
<script src="../../Content/js/common-scripts.js"></script>
<!--this page  script only-->
<script src="../../Content/js/advanced-form-components.js"></script>



}


@section CompanyName
{
    @Session["CompanyName"]
}

@section UserName
{
    @Session["UserName"] @Session["UserSurname"]

}




@section css
{
<link href="../../Content/css/bootstrap.min.css" rel="stylesheet">
<link href="../../Content/css/bootstrap-reset.css" rel="stylesheet">
<link href="../../Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet">
<link href="../../Content/css/style.css" rel="stylesheet">

        <link href="../../Content/css/bootstrap.min.css" rel="stylesheet">
<link href="../../Content/css/bootstrap-reset.css" rel="stylesheet">
<!--external css-->
<link href="../../Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-timepicker/compiled/timepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-colorpicker/css/colorpicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-daterangepicker/daterangepicker-bs3.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-datetimepicker/css/datetimepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/jquery-multi-select/css/multi-select.css" />

<link href="../../Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet">
<link href="../../Content/css/style.css" rel="stylesheet">

}
@section sidebarLi
{

    <li>
        <a href="/Employee/Index">
            <i class="icon-group"></i>
            <span>Home</span>
        </a>

    </li>
}

MVCProje/MVCProje/Views/Claim/_HolidayClaim.cshtml
<label class="col-lg-2 control-label">Start</label>
<div class="col-lg-10" style="padding-bottom:15px">
    <div>
        <input size="5" type="text" value="2018-05-15 12:00" id="_start" readonly="" class="form_datetime form-control">
    </div>
</div>
<label class="col-lg-2 control-label">Finish</label>
<div class="col-lg-10" style="padding-bottom:15px">
    <div>
        <input size="5" type="text" value="2018-05-15 12:00" id="_finish" readonly="" class="form_datetime form-control">
    </div>
</div>

<div>
    <p style="padding-left:1%" id="default-buttons-1" class="default-buttons">

        <a id="button_2" href="javascript:addHoliday();" class="button-back  btn btn-info">Save Holiday</a>
    </p>
</div>

































<script src="../../content/js/jquery.scrollto.min.js"></script>
<script src="../../content/js/jquery.nicescroll.js" type="text/javascript"></script>
<script src="../../Content/js/respond.min.js"></script>
<script type="text/javascript" language="javascript" src="../../Content/assets/advanced-datatable/media/js/jquery.dataTables.js"></script>
<script src="../../Content/js/common-scripts.js"></script>
<script class="include" type="text/javascript" src="../../Content/js/jquery.dcjqaccordion.2.7.js"></script>
<!--this page plugins-->
<script type="text/javascript" src="../../Content/assets/fuelux/js/spinner.min.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-fileupload/bootstrap-fileupload.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-daterangepicker/moment.min.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-daterangepicker/daterangepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script type="text/javascript" src="../../Content/assets/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
<script type="text/javascript" src="../../Content/assets/jquery-multi-select/js/jquery.multi-select.js"></script>
<script type="text/javascript" src="../../Content/assets/jquery-multi-select/js/jquery.quicksearch.js"></script>
<!--common script for all pages-->
<script src="../../Content/js/common-scripts.js"></script>
<!--this page  script only-->
<script src="../../Content/js/advanced-form-components.js"></script>


<link href="../../Content/css/bootstrap.min.css" rel="stylesheet">
<link href="../../Content/css/bootstrap-reset.css" rel="stylesheet">
<link href="../../Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet">
<link href="../../Content/css/style.css" rel="stylesheet">

<link href="../../Content/css/bootstrap.min.css" rel="stylesheet">
<link href="../../Content/css/bootstrap-reset.css" rel="stylesheet">
<!--external css-->
<link href="../../Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-fileupload/bootstrap-fileupload.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-datepicker/css/datepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-timepicker/compiled/timepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-colorpicker/css/colorpicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-daterangepicker/daterangepicker-bs3.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/bootstrap-datetimepicker/css/datetimepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/assets/jquery-multi-select/css/multi-select.css" />

<link href="../../Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet">
<link href="../../Content/assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet">
<link href="../../Content/css/style.css" rel="stylesheet">

MVCProje/MVCProje/Views/Claim/_OtherClaim.cshtml
<label class="col-lg-2 control-label">Details</label>
<div class="col-lg-10">
    <textarea class="form-control" cols="60" rows="5" id="_textArea" name="deneme"></textarea>
</div>
<div>
    <p style="padding-left:1%" id="default-buttons-1" class="default-buttons">

        <a id="button_2" href="javascript:addOther();" class="button-back  btn btn-info">Save Other</a>
    </p>
</div>